export const endpoints = {
  login: "/do_login",
  canUserPullReport: "/canUserPullReport",
  getALLReportGroup: "/getALLReportGroup",
  getAssignedExams: "/getAssignedExams",
  getCareerClusterExam: "/getCareerClusterExam",
  getReasoningExam: "/getQuestionsByExam",
  saveExamResults: "/saveExamResults",
  saveCareerCluster: "/saveCareerCluster",
  saveCareerInterest: "/saveCareerInterest",
  savePsycometricExam: "/savePsycometric",
  getCareerClusterExam: "/getCareerClusterExam",
  getCareerInterestQuestions: "/getCareerSurvey",
  getPsychometricInterest: "/getPsychometricInterest",
  getCareerExamTypesForUser: "/getCareerExamTypesForUser",
};
